# Generated by Django 2.0.5 on 2019-04-13 07:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='课程名称')),
                ('classes', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('opened', models.SmallIntegerField(choices=[(0, '公开'), (1, '不公开')], default=0, verbose_name='公开状态')),
            ],
            options={
                'verbose_name': 'Course Profile',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.SmallIntegerField(choices=[(0, '不可编辑'), (1, '可编辑')], default=1, verbose_name='编辑状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='project.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Handin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('file', models.FileField(blank=True, upload_to=project.models.user_directory_path)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '作答',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('file', models.FileField(blank=True, upload_to=project.models.user_directory_path)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=60, verbose_name='slug')),
                ('published', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='作业状态')),
                ('group', models.SmallIntegerField(choices=[(0, '个人'), (1, '小组')], default=0, verbose_name='组队状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='project.Course')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, '学生'), (1, '教师')], default=0, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后更改时间')),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to=project.models.user_directory_path)),
                ('classes', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='project.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后更改时间')),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to=project.models.user_directory_path)),
                ('ranks', models.CharField(default='无', max_length=50, verbose_name='职称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='project.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='handin',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Student'),
        ),
        migrations.AddField(
            model_name='handin',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Homework'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='project.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, to='project.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, to='project.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='project.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='project.Homework'),
        ),
    ]
