# Generated by Django 2.0.5 on 2019-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classes',
            field=models.CharField(default='', max_length=50, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
