# Generated by Django 2.0.5 on 2019-04-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190413_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='handin',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Course'),
            preserve_default=False,
        ),
    ]
